# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('Content', models.TextField(verbose_name='CONTENT')),
            ],
        ),
    ]
